
%(c) 2013 The Polywell Guy - http://thepolywellblog.blogspot.com/


Parmeters = struct('a', 0, 'Mu', 0, 'Current', 0, 'Turns', 0);
Parmeters.a = 0.127;
Parmeters.Mu = 0.00000125663706;
Parmeters.Current = 4000;
Parmeters.Turns = 200;



disp(' ');
disp('Hello!');
disp(' ');
disp('This code finds the vector field, generated by a single ring of current.');
disp('This is displayed in the XY plane, which is fine since the field is radially symmetric.');
disp('It sets up a matrix of points with a height and width centered on the (0,0) point.');
disp('The ring sits along the Y axis.');
disp(' ');

T1 = 'The ring has a radius of :';
T2 = num2str(Parmeters.a);
T3 = ' (Meters)';
disp(strcat(T1,T2,T3));

T1 = 'The ring has :';
T2 = num2str(Parmeters.Current*Parmeters.Turns);
T3 = ' (AmpTurns)';
disp(strcat(T1,T2,T3));
disp(' ');
	    


Hieght = input('Hieght? (suggest: 0.35):');
Width = input('Width? (suggest: 0.65):');
Cells = input('Number of cells? :');


%Bounds of Model (In Meters)
Bounds = struct('XNeg',-(Width/2),'XPos',(Width/2),'YNeg',-(Hieght/2),'YPos',(Hieght/2));

Coordinates = MakeMatrix(Bounds, Cells);
VectorField = CalcField(Coordinates, Parmeters, Cells);



% Vector Plotting:
U = VectorField.XAverage(:,:);
V = VectorField.YAverage(:,:);       
X = Coordinates.XCor(:,:);
Y = Coordinates.YCor(:,:); 

% This scaling number changes the size of the vectors to plot!
Scale = 11;
quiver(X,Y,U,V,Scale);


disp(' ');
disp(' ');
disp('Plotted here: are the Direction Vectors Times the Field strength.');
disp('The direction vectors are generated by this code.  These are saved within VectorField');
disp('The Magnetic field is listed in Gauss and saved within VectorField.');
disp(' ');
disp(' ');

clear('Hieght', 'Width','Cells','X','Y','U','V','T1','T2','T3','Scale');






